
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BANCO_LOCAL BANCO_VISITANTE CADENA CAMBIO CODIGO_EQUIPO COLOR COMA DOS_PUNTOS EQUIPO_LOCAL EQUIPO_VISITANTE FECHA FORMACION_LOCAL FORMACION_VISITANTE GOL GUION NUEVA_LINEA NUMERO PARENTESIS_ABRE PARENTESIS_CIERRA PUNTO_COMA TARJETA TIEMPO TITULARES_LOCAL TITULARES_VISITANTEpartido : FECHA fecha\n               | EQUIPO_LOCAL CODIGO_EQUIPO\n               | EQUIPO_VISITANTE CODIGO_EQUIPO\n               | FORMACION_LOCAL formacion\n               | FORMACION_VISITANTE formacion\n               | TITULARES_LOCAL lista_numeros\n               | TITULARES_VISITANTE lista_numeros\n               | BANCO_LOCAL lista_numeros\n               | BANCO_VISITANTE lista_numeros\n               | eventofecha : CADENAformacion : NUMERO GUION NUMERO GUION NUMEROlista_numeros : NUMERO\n                     | NUMERO COMA lista_numerosevento : gol\n              | tarjeta\n              | cambiogol : GOL CODIGO_EQUIPO COMA TIEMPO COMA NUMERO COMA NUMERO\n           | GOL CODIGO_EQUIPO COMA TIEMPO COMA NUMEROtarjeta : TARJETA CODIGO_EQUIPO COMA TIEMPO COMA NUMERO COMA COLORcambio : CAMBIO CODIGO_EQUIPO COMA TIEMPO COMA NUMERO COMA NUMERO'
    
_lr_action_items = {'FECHA':([0,],[2,]),'EQUIPO_LOCAL':([0,],[3,]),'EQUIPO_VISITANTE':([0,],[4,]),'FORMACION_LOCAL':([0,],[5,]),'FORMACION_VISITANTE':([0,],[6,]),'TITULARES_LOCAL':([0,],[7,]),'TITULARES_VISITANTE':([0,],[8,]),'BANCO_LOCAL':([0,],[9,]),'BANCO_VISITANTE':([0,],[10,]),'GOL':([0,],[15,]),'TARJETA':([0,],[16,]),'CAMBIO':([0,],[17,]),'$end':([1,11,12,13,14,18,19,20,21,22,24,25,26,27,28,29,39,47,48,54,55,56,],[0,-10,-15,-16,-17,-1,-11,-2,-3,-4,-5,-6,-13,-7,-8,-9,-14,-12,-19,-18,-20,-21,]),'CADENA':([2,],[19,]),'CODIGO_EQUIPO':([3,4,15,16,17,],[20,21,30,31,32,]),'NUMERO':([5,6,7,8,9,10,33,34,43,44,45,46,51,53,],[23,23,26,26,26,26,38,26,47,48,49,50,54,56,]),'GUION':([23,38,],[33,43,]),'COMA':([26,30,31,32,40,41,42,48,49,50,],[34,35,36,37,44,45,46,51,52,53,]),'TIEMPO':([35,36,37,],[40,41,42,]),'COLOR':([52,],[55,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'partido':([0,],[1,]),'evento':([0,],[11,]),'gol':([0,],[12,]),'tarjeta':([0,],[13,]),'cambio':([0,],[14,]),'fecha':([2,],[18,]),'formacion':([5,6,],[22,24,]),'lista_numeros':([7,8,9,10,34,],[25,27,28,29,39,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> partido","S'",1,None,None,None),
  ('partido -> FECHA fecha','partido',2,'p_partido','dsl_externo.py',141),
  ('partido -> EQUIPO_LOCAL CODIGO_EQUIPO','partido',2,'p_partido','dsl_externo.py',142),
  ('partido -> EQUIPO_VISITANTE CODIGO_EQUIPO','partido',2,'p_partido','dsl_externo.py',143),
  ('partido -> FORMACION_LOCAL formacion','partido',2,'p_partido','dsl_externo.py',144),
  ('partido -> FORMACION_VISITANTE formacion','partido',2,'p_partido','dsl_externo.py',145),
  ('partido -> TITULARES_LOCAL lista_numeros','partido',2,'p_partido','dsl_externo.py',146),
  ('partido -> TITULARES_VISITANTE lista_numeros','partido',2,'p_partido','dsl_externo.py',147),
  ('partido -> BANCO_LOCAL lista_numeros','partido',2,'p_partido','dsl_externo.py',148),
  ('partido -> BANCO_VISITANTE lista_numeros','partido',2,'p_partido','dsl_externo.py',149),
  ('partido -> evento','partido',1,'p_partido','dsl_externo.py',150),
  ('fecha -> CADENA','fecha',1,'p_fecha','dsl_externo.py',154),
  ('formacion -> NUMERO GUION NUMERO GUION NUMERO','formacion',5,'p_formacion','dsl_externo.py',158),
  ('lista_numeros -> NUMERO','lista_numeros',1,'p_lista_numeros','dsl_externo.py',162),
  ('lista_numeros -> NUMERO COMA lista_numeros','lista_numeros',3,'p_lista_numeros','dsl_externo.py',163),
  ('evento -> gol','evento',1,'p_evento','dsl_externo.py',170),
  ('evento -> tarjeta','evento',1,'p_evento','dsl_externo.py',171),
  ('evento -> cambio','evento',1,'p_evento','dsl_externo.py',172),
  ('gol -> GOL CODIGO_EQUIPO COMA TIEMPO COMA NUMERO COMA NUMERO','gol',8,'p_gol','dsl_externo.py',176),
  ('gol -> GOL CODIGO_EQUIPO COMA TIEMPO COMA NUMERO','gol',6,'p_gol','dsl_externo.py',177),
  ('tarjeta -> TARJETA CODIGO_EQUIPO COMA TIEMPO COMA NUMERO COMA COLOR','tarjeta',8,'p_tarjeta','dsl_externo.py',196),
  ('cambio -> CAMBIO CODIGO_EQUIPO COMA TIEMPO COMA NUMERO COMA NUMERO','cambio',8,'p_cambio','dsl_externo.py',206),
]
